<# Add the console companion to the manifest generated by msix:build.
   The package's standard execution_alias option targets the GUI executable.
   Keep the GUI's AUMID, protocol, startup task and COM registrations intact. #>
[CmdletBinding()]
param([Parameter(Mandatory)][string]$ManifestPath)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$document = [xml](Get-Content -LiteralPath $ManifestPath -Raw)
$foundation = 'http://schemas.microsoft.com/appx/manifest/foundation/windows10'
$uap3 = 'http://schemas.microsoft.com/appx/manifest/uap/windows10/3'
$desktop = 'http://schemas.microsoft.com/appx/manifest/desktop/windows10'
$namespaces = [Xml.XmlNamespaceManager]::new($document.NameTable)
$namespaces.AddNamespace('p', $foundation)
$namespaces.AddNamespace('uap', 'http://schemas.microsoft.com/appx/manifest/uap/windows10')
$app = $document.SelectSingleNode('/p:Package/p:Applications/p:Application[@Id="ghostcopy"]', $namespaces)
if (-not $app -or $app.GetAttribute('Executable') -ne 'ghostcopy.exe') {
    throw 'Unexpected GUI application identity; refusing to patch the manifest.'
}
$extensions = $app.SelectSingleNode('p:Extensions', $namespaces)
if (-not $extensions) { throw 'Expected the existing GhostCopy integrations.' }
$aliases = @($extensions.SelectNodes('*[@Category="windows.appExecutionAlias"]'))
foreach ($alias in $aliases) {
    if ($alias.GetAttribute('Executable') -ne 'ghostcopy-agent.exe') {
        throw 'An execution alias already targets another executable.'
    }
    [void]$extensions.RemoveChild($alias)
}
[void]$document.DocumentElement.SetAttribute('xmlns:uap3', $uap3)
[void]$document.DocumentElement.SetAttribute('xmlns:desktop', $desktop)
$ignorable = @($document.DocumentElement.GetAttribute('IgnorableNamespaces') -split '\s+' |
    Where-Object { $_ }) + @('uap3', 'desktop')
$document.DocumentElement.SetAttribute('IgnorableNamespaces', (($ignorable | Select-Object -Unique) -join ' '))
# Use the classic desktop alias extension: the target PE is already a console
# executable. A separate AppListEntry=none application needs a Store waiver.
$applications = $app.ParentNode
$previous = $applications.SelectSingleNode('p:Application[@Id="GhostCopyCli"]', $namespaces)
if ($previous) { [void]$applications.RemoveChild($previous) }
$extension = $document.CreateElement('uap3', 'Extension', $uap3)
$extension.SetAttribute('Category', 'windows.appExecutionAlias')
$extension.SetAttribute('Executable', 'ghostcopy-agent.exe')
$extension.SetAttribute('EntryPoint', 'Windows.FullTrustApplication')
$appAlias = $document.CreateElement('uap3', 'AppExecutionAlias', $uap3)
$command = $document.CreateElement('desktop', 'ExecutionAlias', $desktop)
$command.SetAttribute('Alias', 'ghostcopy.exe')
[void]$appAlias.AppendChild($command)
[void]$extension.AppendChild($appAlias)
[void]$extensions.AppendChild($extension)
$document.Save([IO.Path]::GetFullPath($ManifestPath))
