-- Recovered from production migration history on 2026-09-14.
--
-- This DDL was applied to production on 2025-12-28 16:48:52 through the Supabase
-- dashboard, which recorded it in supabase_migrations.schema_migrations
-- but never wrote a file to this directory. The SQL below is that
-- recorded statement text, verbatim.
--
-- It is ALREADY APPLIED. The file exists so the CLI migration history
-- matches production and `supabase db push` can manage future changes.
-- Do not edit it and do not re-run it by hand.

-- Create non-partitioned clipboard_test table to verify partitioning is the issue
CREATE TABLE clipboard_test (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users NOT NULL,
  content text NOT NULL,
  device_name text,
  device_type device_type_enum NOT NULL,
  target_device_type device_type_enum,
  is_public boolean DEFAULT false NOT NULL,
  is_encrypted boolean DEFAULT false NOT NULL,
  encryption_version integer,
  created_at timestamptz DEFAULT timezone('utc', now()) NOT NULL,
  expires_at timestamptz,
  CONSTRAINT enforce_private_only CHECK (is_public = false)
);

-- Enable RLS (same as clipboard)
ALTER TABLE clipboard_test ENABLE ROW LEVEL SECURITY;

-- Add same RLS policies as clipboard
CREATE POLICY users_view_own_clipboard_only ON clipboard_test
  FOR SELECT TO authenticated
  USING (user_id = auth.uid());

CREATE POLICY users_insert_own_clipboard ON clipboard_test
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY users_update_own_clipboard ON clipboard_test
  FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

CREATE POLICY users_delete_own_clipboard ON clipboard_test
  FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- Add to realtime publication
ALTER PUBLICATION supabase_realtime ADD TABLE clipboard_test;

-- Grant SELECT to supabase_realtime_admin
GRANT SELECT ON clipboard_test TO supabase_realtime_admin;
