-- Recovered from production migration history on 2026-09-14.
--
-- This DDL was applied to production on 2025-11-27 04:42:11 through the Supabase
-- dashboard, which recorded it in supabase_migrations.schema_migrations
-- but never wrote a file to this directory. The SQL below is that
-- recorded statement text, verbatim.
--
-- It is ALREADY APPLIED. The file exists so the CLI migration history
-- matches production and `supabase db push` can manage future changes.
-- Do not edit it and do not re-run it by hand.

-- Create clipboard table
CREATE TABLE clipboard (
  id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id uuid REFERENCES auth.users NOT NULL,
  content text NOT NULL,
  device_name text,
  device_type text NOT NULL,
  is_public boolean DEFAULT false,
  created_at timestamptz DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE clipboard ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view own items" ON clipboard
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own items" ON clipboard
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete own items" ON clipboard
  FOR DELETE USING (auth.uid() = user_id);

-- Index for efficient history queries
CREATE INDEX idx_clipboard_user_created ON clipboard(user_id, created_at DESC);
